; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

; Function Attrs: norecurse nounwind readnone
define fastcc <512 x i32> @d2ui(<512 x double> %a) {
; CHECK-LABEL: d2ui:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vcvt.l.d.rz %v2, %v0
; CHECK-NEXT:    vcvt.l.d.rz %v3, %v1
; CHECK-NEXT:    vshf %v0, %v3, %v2, 13
; CHECK-NEXT:    b.l.t (, %s10)
entry:
  %conv = fptoui <512 x double> %a to <512 x i32>
  ret <512 x i32> %conv
}
