; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown | FileCheck %s

@v512i32 = common dso_local local_unnamed_addr global <512 x i32> zeroinitializer, align 16

; Function Attrs: norecurse nounwind readonly
define fastcc void @storev512i32(<512 x i32>* nocapture, <512 x i32>) {
; CHECK-LABEL: storev512i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    vst %v0, 8, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  store <512 x i32> %1, <512 x i32>* %0, align 16
  ret void
}

; Function Attrs: norecurse nounwind readonly
define fastcc void @storev512i32stk(<512 x i32>) {
; CHECK-LABEL: storev512i32stk:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s11, -2048(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    lea %s1, (, %s11)
; CHECK-NEXT:    vst %v0, 8, %s1
; CHECK-NEXT:    lea %s11, 2048(, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
  %addr = alloca <512 x i32>, align 16
  store <512 x i32> %0, <512 x i32>* %addr, align 16
  ret void
}

; Function Attrs: norecurse nounwind readonly
define fastcc void @storev512i32com(<512 x i32>) {
; CHECK-LABEL: storev512i32com:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    lea %s1, v512i32@lo
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    lea.sl %s1, v512i32@hi(, %s1)
; CHECK-NEXT:    vst %v0, 8, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  store <512 x i32> %0, <512 x i32>* @v512i32, align 16
  ret void
}
