; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown | FileCheck %s

; Function Attrs: nounwind
define fastcc <1 x i64> @vec_xor_v1f64(<1 x i64> %a, <1 x i64> %b) {
; CHECK-LABEL: vec_xor_v1f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xor %s0, %s0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <1 x i64> %a, %b
  ret <1 x i64> %r
}

; Function Attrs: nounwind
define fastcc <2 x i64> @vec_xor_v2f64(<2 x i64> %a, <2 x i64> %b) {
; CHECK-LABEL: vec_xor_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 2, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <2 x i64> %a, %b
  ret <2 x i64> %r
}

; Function Attrs: nounwind
define fastcc <3 x i64> @vec_xor_v3f64(<3 x i64> %a, <3 x i64> %b) {
; CHECK-LABEL: vec_xor_v3f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 3, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <3 x i64> %a, %b
  ret <3 x i64> %r
}

; Function Attrs: nounwind
define fastcc <4 x i64> @vec_xor_v4f64(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: vec_xor_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 4, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <4 x i64> %a, %b
  ret <4 x i64> %r
}

; Function Attrs: nounwind
define fastcc <8 x i64> @vec_xor_v8f64(<8 x i64> %a, <8 x i64> %b) {
; CHECK-LABEL: vec_xor_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 8, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <8 x i64> %a, %b
  ret <8 x i64> %r
}

; Function Attrs: nounwind
define fastcc <16 x i64> @vec_xor_v16f64(<16 x i64> %a, <16 x i64> %b) {
; CHECK-LABEL: vec_xor_v16f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 16, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <16 x i64> %a, %b
  ret <16 x i64> %r
}

; Function Attrs: nounwind
define fastcc <32 x i64> @vec_xor_v32f64(<32 x i64> %a, <32 x i64> %b) {
; CHECK-LABEL: vec_xor_v32f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 32, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <32 x i64> %a, %b
  ret <32 x i64> %r
}

; Function Attrs: nounwind
define fastcc <64 x i64> @vec_xor_v64f64(<64 x i64> %a, <64 x i64> %b) {
; CHECK-LABEL: vec_xor_v64f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 64
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <64 x i64> %a, %b
  ret <64 x i64> %r
}

; Function Attrs: nounwind
define fastcc <128 x i64> @vec_xor_v128f64(<128 x i64> %a, <128 x i64> %b) {
; CHECK-LABEL: vec_xor_v128f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 128
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <128 x i64> %a, %b
  ret <128 x i64> %r
}

; Function Attrs: nounwind
define fastcc <253 x i64> @vec_xor_v253f64(<253 x i64> %a, <253 x i64> %b) {
; CHECK-LABEL: vec_xor_v253f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 253
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <253 x i64> %a, %b
  ret <253 x i64> %r
}

; Function Attrs: nounwind
define fastcc <256 x i64> @vec_xor_v256f64(<256 x i64> %a, <256 x i64> %b) {
; CHECK-LABEL: vec_xor_v256f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <256 x i64> %a, %b
  ret <256 x i64> %r
}

; Function Attrs: nounwind
define fastcc <512 x i64> @vec_xor_v512f64(<512 x i64> %a, <512 x i64> %b) {
; CHECK-LABEL: vec_xor_v512f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v1, %v1, %v3
; CHECK-NEXT:    vxor %v0, %v0, %v2
; CHECK-NEXT:    # kill: def $v0 killed $v0 def $vp0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <512 x i64> %a, %b
  ret <512 x i64> %r
}

; Function Attrs: nounwind
define fastcc <1024 x i64> @vec_xor_v1024f64(<1024 x i64> %a, <1024 x i64> %b) {
; CHECK-LABEL: vec_xor_v1024f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vxor %v1, %v1, %v5
; CHECK-NEXT:    vxor %v0, %v0, %v4
; CHECK-NEXT:    vxor %v3, %v3, %v7
; CHECK-NEXT:    vxor %v2, %v2, %v6
; CHECK-NEXT:    # kill: def $v0 killed $v0 def $vp0
; CHECK-NEXT:    # kill: def $v2 killed $v2 def $vp1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <1024 x i64> %a, %b
  ret <1024 x i64> %r
}


; Function Attrs: nounwind
define fastcc <1 x i32> @vec_xor_v1f32(<1 x i32> %a, <1 x i32> %b) {
; CHECK-LABEL: vec_xor_v1f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xor %s0, %s0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <1 x i32> %a, %b
  ret <1 x i32> %r
}

; Function Attrs: nounwind
define fastcc <2 x i32> @vec_xor_v2f32(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: vec_xor_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 2, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <2 x i32> %a, %b
  ret <2 x i32> %r
}

; Function Attrs: nounwind
define fastcc <3 x i32> @vec_xor_v3f32(<3 x i32> %a, <3 x i32> %b) {
; CHECK-LABEL: vec_xor_v3f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 3, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <3 x i32> %a, %b
  ret <3 x i32> %r
}

; Function Attrs: nounwind
define fastcc <4 x i32> @vec_xor_v4f32(<4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: vec_xor_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 4, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <4 x i32> %a, %b
  ret <4 x i32> %r
}

; Function Attrs: nounwind
define fastcc <8 x i32> @vec_xor_v8f32(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: vec_xor_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 8, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <8 x i32> %a, %b
  ret <8 x i32> %r
}

; Function Attrs: nounwind
define fastcc <16 x i32> @vec_xor_v16f32(<16 x i32> %a, <16 x i32> %b) {
; CHECK-LABEL: vec_xor_v16f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 16, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <16 x i32> %a, %b
  ret <16 x i32> %r
}

; Function Attrs: nounwind
define fastcc <32 x i32> @vec_xor_v32f32(<32 x i32> %a, <32 x i32> %b) {
; CHECK-LABEL: vec_xor_v32f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    or %s0, 32, (0)1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <32 x i32> %a, %b
  ret <32 x i32> %r
}

; Function Attrs: nounwind
define fastcc <64 x i32> @vec_xor_v64f32(<64 x i32> %a, <64 x i32> %b) {
; CHECK-LABEL: vec_xor_v64f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 64
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <64 x i32> %a, %b
  ret <64 x i32> %r
}

; Function Attrs: nounwind
define fastcc <128 x i32> @vec_xor_v128f32(<128 x i32> %a, <128 x i32> %b) {
; CHECK-LABEL: vec_xor_v128f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 128
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <128 x i32> %a, %b
  ret <128 x i32> %r
}

; Function Attrs: nounwind
define fastcc <253 x i32> @vec_xor_v253f32(<253 x i32> %a, <253 x i32> %b) {
; CHECK-LABEL: vec_xor_v253f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 253
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <253 x i32> %a, %b
  ret <253 x i32> %r
}

; Function Attrs: nounwind
define fastcc <256 x i32> @vec_xor_v256f32(<256 x i32> %a, <256 x i32> %b) {
; CHECK-LABEL: vec_xor_v256f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor.lo %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <256 x i32> %a, %b
  ret <256 x i32> %r
}

; Function Attrs: nounwind
define fastcc <512 x i32> @vec_xor_v512f32(<512 x i32> %a, <512 x i32> %b) {
; CHECK-LABEL: vec_xor_v512f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <512 x i32> %a, %b
  ret <512 x i32> %r
}

; Function Attrs: nounwind
define fastcc <1024 x i32> @vec_xor_v1024f32(<1024 x i32> %a, <1024 x i32> %b) {
; CHECK-LABEL: vec_xor_v1024f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvxor %v0, %v0, %v2
; CHECK-NEXT:    pvxor %v1, %v1, %v3
; CHECK-NEXT:    b.l.t (, %s10)
  %r = xor <1024 x i32> %a, %b
  ret <1024 x i32> %r
}
