; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

;; 256 x double

; Function Attrs: nounwind
define fastcc <256 x double> @vec_arcp_fdiv_v256f64(<256 x double> %x, <256 x double> %y) {
; CHECK-LABEL: vec_arcp_fdiv_v256f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vrcp.d %v1, %v1
; CHECK-NEXT:    vfmul.d %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = fdiv arcp <256 x double> %x, %y
  ret <256 x double> %r
}

; Function Attrs: nounwind
define fastcc <256 x double> @vec_arcp_fma_fdiv_v256f64(<256 x double> %x, <256 x double> %y, <256 x double> %z) {
; CHECK-LABEL: vec_arcp_fma_fdiv_v256f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vrcp.d %v1, %v1
; CHECK-NEXT:    vfmad.d %v0, %v2, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %tmp = fdiv arcp contract <256 x double> %x, %y
  %r = fadd <256 x double> %tmp, %z
  ret <256 x double> %r
}
