; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --march=ve %s -o=/dev/stdout | FileCheck %s

define fastcc void @test_vp_harness(<512 x i32>* %Out, <512 x i32> %i0) {
; CHECK-LABEL: test_vp_harness:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    vst %v0, 8, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  store <512 x i32> %i0, <512 x i32>* %Out
  ret void
}

define fastcc void @test_vp_fadd_fsub_fmul_fneg_fma(<512 x float>* %Out, <512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_vp_fadd_fsub_fmul_fneg_fma:
; CHECK:       # %bb.0:
; CHECK-NEXT:    adds.w.sx %s1, 1, %s1
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    srl %s1, %s1, 1
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    pvfadd %v2, %v0, %v1
; CHECK-NEXT:    pvfsub %v3, %v0, %v1
; CHECK-NEXT:    pvfmul %v2, %v2, %v3
; CHECK-NEXT:    pvfmad %v0, %v2, %v0, %v1
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    vst %v0, 8, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  %r0 = call <512 x float> @llvm.vp.fadd.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
  %r1 = call <512 x float> @llvm.vp.fsub.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
  %r2 = call <512 x float> @llvm.vp.fmul.v512f32(<512 x float> %r0, <512 x float> %r1, <512 x i1> %m, i32 %n)
  ; %r3 = call <512 x float> @llvm.vp.fneg.v512f32(<512 x float> %r2, <512 x i1> %m, i32 %n)
  %r4 = call <512 x float> @llvm.vp.fma.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x float> %r2, <512 x i1> %m, i32 %n)
  store <512 x float> %r4, <512 x float>* %Out
  ret void
}

define fastcc void @test_vp_fdiv(<512 x float>* %Out, <512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_vp_fdiv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s2, %s1, (32)0
; CHECK-NEXT:    srl %s2, %s2, 1
; CHECK-NEXT:    lvl %s2
; CHECK-NEXT:    vshf %v2, %v1, %v1, 4
; CHECK-NEXT:    vshf %v3, %v0, %v0, 4
; CHECK-NEXT:    adds.w.sx %s1, 1, %s1
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    srl %s1, %s1, 1
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vfdiv.s %v2, %v3, %v2, %vm3
; CHECK-NEXT:    vfdiv.s %v0, %v0, %v1, %vm2
; CHECK-NEXT:    vshf %v0, %v2, %v0, 8
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    vst %v0, 8, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  %r0 = call <512 x float> @llvm.vp.fdiv.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
  store <512 x float> %r0, <512 x float>* %Out
  ret void
}

define fastcc void @test_vp_fmin_fmax(<512 x float>* %O1, <512 x float>* %O2, <512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_vp_fmin_fmax:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s3, %s2, (32)0
; CHECK-NEXT:    srl %s3, %s3, 1
; CHECK-NEXT:    lvl %s3
; CHECK-NEXT:    vshf %v2, %v1, %v1, 4
; CHECK-NEXT:    vshf %v3, %v0, %v0, 4
; CHECK-NEXT:    adds.w.sx %s2, 1, %s2
; CHECK-NEXT:    and %s2, %s2, (32)0
; CHECK-NEXT:    srl %s2, %s2, 1
; CHECK-NEXT:    lvl %s2
; CHECK-NEXT:    vfmin.s %v4, %v3, %v2
; CHECK-NEXT:    vfmin.s %v5, %v0, %v1
; CHECK-NEXT:    vshf %v4, %v4, %v5, 8
; CHECK-NEXT:    vfmax.s %v2, %v3, %v2
; CHECK-NEXT:    vfmax.s %v0, %v0, %v1
; CHECK-NEXT:    vshf %v0, %v2, %v0, 8
; CHECK-NEXT:    lea %s2, 256
; CHECK-NEXT:    lvl %s2
; CHECK-NEXT:    vshf %v1, %v4, %v4, 4
; CHECK-NEXT:    vst %v1, 8, %s0
; CHECK-NEXT:    vshf %v0, %v0, %v0, 4
; CHECK-NEXT:    vst %v0, 8, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r0 = call <512 x float> @llvm.vp.minnum.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
  %r1 = call <512 x float> @llvm.vp.maxnum.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
  store <512 x float> %r0, <512 x float>* %O1
  store <512 x float> %r1, <512 x float>* %O2
  ret void
}

; define fastcc void @test_vp_frem(<512 x float>* %Out, <512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n) {
;   %r0 = call <512 x float> @llvm.vp.frem.v512f32(<512 x float> %f0, <512 x float> %f1, <512 x i1> %m, i32 %n)
;   store <512 x float> %r0, <512 x float>* %Out
;   ret void
; }

; fp arithmetic
declare <512 x float> @llvm.vp.fadd.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.fsub.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.fmul.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.fdiv.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.fma.v512f32(<512 x float>, <512 x float>, <512 x float>, <512 x i1>, i32)
; TODO
; declare <512 x float> @llvm.vp.frem.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
; declare <512 x float> @llvm.vp.fneg.v512f32(<512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.minnum.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
declare <512 x float> @llvm.vp.maxnum.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
