; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --march=ve -mattr=+vpu %s -o=/dev/stdout | FileCheck %s --check-prefix=CHECK-O0
; RUN: llc -O2 --march=ve -mattr=+vpu %s -o=/dev/stdout | FileCheck %s --check-prefix=CHECK-O2

define fastcc i1 @test_reduce_and(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n) {
; FIXME: The generated code is incorrect!
; CHECK-O0-LABEL: test_reduce_and:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    and %s1, %s1, (32)0
; CHECK-O0-NEXT:    or %s2, 0, %s1
; CHECK-O0-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O0-NEXT:    andm %vm4, %vm3, %vm5
; CHECK-O0-NEXT:    # implicit-def: $vmp1
; CHECK-O0-NEXT:    andm %vm3, %vm0, %vm4
; CHECK-O0-NEXT:    andm %vm2, %vm0, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm2
; CHECK-O0-NEXT:    lvl %s2
; CHECK-O0-NEXT:    pcvm %s3, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm3
; CHECK-O0-NEXT:    pcvm %s1, %vm1
; CHECK-O0-NEXT:    adds.l %s1, %s1, %s3
; CHECK-O0-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-O0-NEXT:    cmpu.w %s2, %s1, %s2
; CHECK-O0-NEXT:    # implicit-def: $sx1
; CHECK-O0-NEXT:    or %s1, 0, %s2
; CHECK-O0-NEXT:    ldz %s1, %s1
; CHECK-O0-NEXT:    srl %s1, %s1, 6
; CHECK-O0-NEXT:    or %s2, 0, %s1
; CHECK-O0-NEXT:    # implicit-def: $sx1
; CHECK-O0-NEXT:    or %s1, 0, %s2
; CHECK-O0-NEXT:    and %s0, %s0, %s1
; CHECK-O0-NEXT:    b.l.t (, %s10)
;
; CHECK-O2-LABEL: test_reduce_and:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    and %s1, %s1, (32)0
; CHECK-O2-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O2-NEXT:    andm %vm3, %vm3, %vm5
; CHECK-O2-NEXT:    lvl %s1
; CHECK-O2-NEXT:    pcvm %s2, %vm1
; CHECK-O2-NEXT:    pcvm %s3, %vm3
; CHECK-O2-NEXT:    adds.l %s2, %s3, %s2
; CHECK-O2-NEXT:    cmpu.w %s1, %s2, %s1
; CHECK-O2-NEXT:    ldz %s1, %s1
; CHECK-O2-NEXT:    srl %s1, %s1, 6
; CHECK-O2-NEXT:    and %s0, %s0, %s1
; CHECK-O2-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.and.v512i1(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_or(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n) {
; CHECK-O0-LABEL: test_reduce_or:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    and %s1, %s1, (32)0
; CHECK-O0-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-O0-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O0-NEXT:    andm %vm4, %vm3, %vm5
; CHECK-O0-NEXT:    # implicit-def: $vmp1
; CHECK-O0-NEXT:    andm %vm3, %vm0, %vm4
; CHECK-O0-NEXT:    andm %vm2, %vm0, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm2
; CHECK-O0-NEXT:    lvl %s1
; CHECK-O0-NEXT:    pcvm %s2, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm3
; CHECK-O0-NEXT:    pcvm %s1, %vm1
; CHECK-O0-NEXT:    adds.l %s1, %s1, %s2
; CHECK-O0-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-O0-NEXT:    cmpu.w %s2, 0, %s1
; CHECK-O0-NEXT:    # implicit-def: $sx1
; CHECK-O0-NEXT:    or %s1, 0, %s2
; CHECK-O0-NEXT:    srl %s1, %s1, 31
; CHECK-O0-NEXT:    or %s2, 0, %s1
; CHECK-O0-NEXT:    # implicit-def: $sx1
; CHECK-O0-NEXT:    or %s1, 0, %s2
; CHECK-O0-NEXT:    or %s0, %s0, %s1
; CHECK-O0-NEXT:    b.l.t (, %s10)
;
; CHECK-O2-LABEL: test_reduce_or:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    and %s1, %s1, (32)0
; CHECK-O2-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O2-NEXT:    andm %vm3, %vm3, %vm5
; CHECK-O2-NEXT:    lvl %s1
; CHECK-O2-NEXT:    pcvm %s2, %vm1
; CHECK-O2-NEXT:    pcvm %s1, %vm3
; CHECK-O2-NEXT:    adds.l %s1, %s1, %s2
; CHECK-O2-NEXT:    cmpu.w %s1, 0, %s1
; CHECK-O2-NEXT:    srl %s1, %s1, 31
; CHECK-O2-NEXT:    or %s0, %s0, %s1
; CHECK-O2-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.or.v512i1(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_xor(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n) {
; CHECK-O0-LABEL: test_reduce_xor:
; CHECK-O0:       # %bb.0:
; CHECK-O0-NEXT:    and %s1, %s1, (32)0
; CHECK-O0-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-O0-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O0-NEXT:    andm %vm4, %vm3, %vm5
; CHECK-O0-NEXT:    # implicit-def: $vmp1
; CHECK-O0-NEXT:    andm %vm3, %vm0, %vm4
; CHECK-O0-NEXT:    andm %vm2, %vm0, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm2
; CHECK-O0-NEXT:    lvl %s1
; CHECK-O0-NEXT:    pcvm %s2, %vm1
; CHECK-O0-NEXT:    andm %vm1, %vm0, %vm3
; CHECK-O0-NEXT:    pcvm %s1, %vm1
; CHECK-O0-NEXT:    adds.l %s1, %s1, %s2
; CHECK-O0-NEXT:    and %s1, 1, %s1
; CHECK-O0-NEXT:    xor %s0, %s0, %s1
; CHECK-O0-NEXT:    b.l.t (, %s10)
;
; CHECK-O2-LABEL: test_reduce_xor:
; CHECK-O2:       # %bb.0:
; CHECK-O2-NEXT:    and %s1, %s1, (32)0
; CHECK-O2-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-O2-NEXT:    andm %vm3, %vm3, %vm5
; CHECK-O2-NEXT:    lvl %s1
; CHECK-O2-NEXT:    pcvm %s2, %vm1
; CHECK-O2-NEXT:    pcvm %s1, %vm3
; CHECK-O2-NEXT:    adds.l %s1, %s1, %s2
; CHECK-O2-NEXT:    and %s1, 1, %s1
; CHECK-O2-NEXT:    xor %s0, %s0, %s1
; CHECK-O2-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.xor.v512i1(i1 %s, <512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

declare i1 @llvm.vp.reduce.and.v512i1(i1, <512 x i1>, <512 x i1>, i32)
declare i1 @llvm.vp.reduce.xor.v512i1(i1, <512 x i1>, <512 x i1>, i32)
declare i1 @llvm.vp.reduce.or.v512i1(i1, <512 x i1>, <512 x i1>, i32)
