; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --march=ve -mattr=+packed %s -o=/dev/stdout | FileCheck %s

define fastcc i1 @test_reduce_and(<512 x i1> %v, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_reduce_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # implicit-def: $vmp4
; CHECK-NEXT:    andm %vm9, %vm0, %vm5
; CHECK-NEXT:    andm %vm8, %vm0, %vm4
; CHECK-NEXT:    # implicit-def: $vmp3
; CHECK-NEXT:    andm %vm7, %vm0, %vm3
; CHECK-NEXT:    andm %vm6, %vm0, %vm2
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    or %s1, 0, %s0
; CHECK-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    pcvm %s2, %vm1
; CHECK-NEXT:    andm %vm1, %vm3, %vm5
; CHECK-NEXT:    pcvm %s0, %vm1
; CHECK-NEXT:    adds.l %s0, %s0, %s2
; CHECK-NEXT:    # kill: def $sw0 killed $sw0 killed $sx0
; CHECK-NEXT:    cmps.w.zx %s1, %s0, %s1
; CHECK-NEXT:    # implicit-def: $sx0
; CHECK-NEXT:    or %s0, 0, %s1
; CHECK-NEXT:    ldz %s0, %s0
; CHECK-NEXT:    srl %s0, %s0, 6
; CHECK-NEXT:    or %s1, 0, %s0
; CHECK-NEXT:    # implicit-def: $sx0
; CHECK-NEXT:    or %s0, 0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.and.v512i1(<512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_or(<512 x i1> %v, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_reduce_or:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # implicit-def: $vmp4
; CHECK-NEXT:    andm %vm9, %vm0, %vm5
; CHECK-NEXT:    andm %vm8, %vm0, %vm4
; CHECK-NEXT:    # implicit-def: $vmp3
; CHECK-NEXT:    andm %vm7, %vm0, %vm3
; CHECK-NEXT:    andm %vm6, %vm0, %vm2
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    # kill: def $sw0 killed $sw0 killed $sx0
; CHECK-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pcvm %s1, %vm1
; CHECK-NEXT:    andm %vm1, %vm3, %vm5
; CHECK-NEXT:    pcvm %s0, %vm1
; CHECK-NEXT:    adds.l %s0, %s0, %s1
; CHECK-NEXT:    # kill: def $sw0 killed $sw0 killed $sx0
; CHECK-NEXT:    cmpu.w %s1, 0, %s0
; CHECK-NEXT:    # implicit-def: $sx0
; CHECK-NEXT:    or %s0, 0, %s1
; CHECK-NEXT:    srl %s0, %s0, 31
; CHECK-NEXT:    or %s1, 0, %s0
; CHECK-NEXT:    # implicit-def: $sx0
; CHECK-NEXT:    or %s0, 0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.or.v512i1(<512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_xor(<512 x i1> %v, <512 x i1> %m, i32 %n) {
; CHECK-LABEL: test_reduce_xor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # implicit-def: $vmp4
; CHECK-NEXT:    andm %vm9, %vm0, %vm5
; CHECK-NEXT:    andm %vm8, %vm0, %vm4
; CHECK-NEXT:    # implicit-def: $vmp3
; CHECK-NEXT:    andm %vm7, %vm0, %vm3
; CHECK-NEXT:    andm %vm6, %vm0, %vm2
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    # kill: def $sw0 killed $sw0 killed $sx0
; CHECK-NEXT:    andm %vm1, %vm2, %vm4
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pcvm %s1, %vm1
; CHECK-NEXT:    andm %vm1, %vm3, %vm5
; CHECK-NEXT:    pcvm %s0, %vm1
; CHECK-NEXT:    adds.l %s0, %s0, %s1
; CHECK-NEXT:    and %s0, 1, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.xor.v512i1(<512 x i1> %v, <512 x i1> %m, i32 %n)
  ret i1 %r
}

declare i1 @llvm.vp.reduce.and.v512i1(<512 x i1>, <512 x i1> mask, i32 vlen)
declare i1 @llvm.vp.reduce.xor.v512i1(<512 x i1>, <512 x i1> mask, i32 vlen)
declare i1 @llvm.vp.reduce.or.v512i1(<512 x i1>, <512 x i1> mask, i32 vlen)
