; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

; Function Attrs: nounwind
define fastcc <512 x float> @vec_frcp_v512f32(<512 x float> %x, <512 x i1> %M, i32 %L) {
; CHECK-LABEL: vec_frcp_v512f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $vm2 killed $vm2 killed $vmp1 def $vmp1
; CHECK-NEXT:    adds.w.sx %s0, 1, %s0
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    srl %s0, %s0, 1
; CHECK-NEXT:    # kill: def $vm3 killed $vm3 killed $vmp1 def $vmp1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvrcp %v0, %v0, %vm2
; CHECK-NEXT:    b.l.t (, %s10)
  %sz = insertelement <512 x float> undef, float 1.0, i32 0
  %vone = shufflevector <512 x float> %sz, <512 x float> poison, <512 x i32> zeroinitializer
  %r = call fast <512 x float> @llvm.vp.fdiv.v512f32(<512 x float> %vone, <512 x float> %x, <512 x i1> %M, i32 %L)
  ret <512 x float> %r
}

declare <512 x float> @llvm.vp.fdiv.v512f32(<512 x float>, <512 x float>, <512 x i1>, i32)
