; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown | FileCheck %s

define fastcc <512 x double> @vec_fpext_v512_float_to_double(<512 x float> %a) {
; CHECK-LABEL: vec_fpext_v512_float_to_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vshf %v1, %v0, %v0, 4
; CHECK-NEXT:    vcvt.d.s %v1, %v1
; CHECK-NEXT:    vcvt.d.s %v0, %v0
; CHECK-NEXT:    # kill: def $v0 killed $v0 def $vp0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = fpext <512 x float> %a to <512 x double>
  ret <512 x double> %r
}

declare <512 x double> @llvm.vp.fpext.v512f32.v512f64(<512 x float>, <512 x i1>, i32)

define fastcc <512 x double> @vec_vpfpext_v512_float_to_double(<512 x float> %a, <512 x i1> %m, i32 %avl) {
; CHECK-LABEL: vec_vpfpext_v512_float_to_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s1, %s0, (32)0
; CHECK-NEXT:    srl %s1, %s1, 1
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vshf %v1, %v0, %v0, 4
; CHECK-NEXT:    adds.w.sx %s0, 1, %s0
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    srl %s0, %s0, 1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vcvt.d.s %v1, %v1, %vm3
; CHECK-NEXT:    vcvt.d.s %v0, %v0, %vm2
; CHECK-NEXT:    # kill: def $v0 killed $v0 def $vp0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call <512 x double> @llvm.vp.fpext.v512f32.v512f64(<512 x float> %a, <512 x i1> %m, i32 %avl)
  ret <512 x double> %r
}

