; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown | FileCheck %s

define fastcc <512 x float> @vec_fptrunc_v512_double_to_float(<512 x double> %a) {
; CHECK-LABEL: vec_fptrunc_v512_double_to_float:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vcvt.s.d %v0, %v0
; CHECK-NEXT:    vcvt.s.d %v1, %v1
; CHECK-NEXT:    vshf %v0, %v1, %v0, 8
; CHECK-NEXT:    b.l.t (, %s10)
  %r = fptrunc <512 x double> %a to <512 x float>
  ret <512 x float> %r
}

declare <512 x float> @llvm.vp.fptrunc.v512f32.v512f64(<512 x double>, <512 x i1>, i32)

define fastcc <512 x float> @vec_vpfptrunc_v512_double_to_float(<512 x double> %a, <512 x i1> %m, i32 %avl) {
; CHECK-LABEL: vec_vpfptrunc_v512_double_to_float:
; CHECK:       # %bb.0:
; CHECK-NEXT:    adds.w.sx %s0, 1, %s0
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    srl %s0, %s0, 1
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vcvt.s.d %v0, %v0, %vm2
; CHECK-NEXT:    vcvt.s.d %v1, %v1, %vm3
; CHECK-NEXT:    vshf %v0, %v1, %v0, 8
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call <512 x float> @llvm.vp.fptrunc.v512f32.v512f64(<512 x double> %a, <512 x i1> %m, i32 %avl)
  ret <512 x float> %r
}

