; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

; Function Attrs: norecurse nounwind readonly
define fastcc <256 x float> @fmadvvv256f32(<256 x float> %y,  <256 x float> %z, <256 x float> %w) {
; CHECK-LABEL: fmadvvv256f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vfmad.s %v0, %v0, %v1, %v2
; CHECK-NEXT:    b.l.t (, %s10)
  %ret = fmul fast <256 x float> %z, %w
  %ret2 = fadd fast <256 x float> %ret, %y
  ret <256 x float> %ret2
}
