; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve -mattr=+vpu | FileCheck %s

; <256 x i32>

; Function Attrs: nounwind
define fastcc <256 x i32> @urem_vv_v256i32(<256 x i32> %x, <256 x i32> %y) {
; CHECK-LABEL: urem_vv_v256i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vdivu.w %v2, %v0, %v1
; CHECK-NEXT:    vmuls.w.sx %v1, %v2, %v1
; CHECK-NEXT:    vsubs.w.sx %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %z = urem <256 x i32> %x, %y
  ret <256 x i32> %z
}

; Function Attrs: nounwind
define fastcc <256 x i32> @urem_sv_v256i32(i32 %x, <256 x i32> %y) {
; CHECK-LABEL: urem_sv_v256i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vdivu.w %v1, %s0, %v0
; CHECK-NEXT:    vmuls.w.sx %v0, %v1, %v0
; CHECK-NEXT:    vsubs.w.sx %v0, %s0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %xins = insertelement <256 x i32> undef, i32 %x, i32 0
  %vx = shufflevector <256 x i32> %xins, <256 x i32> undef, <256 x i32> zeroinitializer
  %z = urem <256 x i32> %vx, %y
  ret <256 x i32> %z
}

; Function Attrs: nounwind
define fastcc <256 x i32> @urem_vs_v256i32(<256 x i32> %x, i32 %y) {
; CHECK-LABEL: urem_vs_v256i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vdivu.w %v1, %v0, %s0
; CHECK-NEXT:    vmuls.w.sx %v1, %s0, %v1
; CHECK-NEXT:    vsubs.w.sx %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %yins = insertelement <256 x i32> undef, i32 %y, i32 0
  %vy = shufflevector <256 x i32> %yins, <256 x i32> undef, <256 x i32> zeroinitializer
  %z = urem <256 x i32> %x, %vy
  ret <256 x i32> %z
}



; <256 x i64>

; Function Attrs: nounwind
define fastcc <256 x i64> @urem_vv_v256i64(<256 x i64> %x, <256 x i64> %y) {
; CHECK-LABEL: urem_vv_v256i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vdivu.l %v2, %v0, %v1
; CHECK-NEXT:    vmuls.l %v1, %v2, %v1
; CHECK-NEXT:    vsubs.l %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %z = urem <256 x i64> %x, %y
  ret <256 x i64> %z
}

; Function Attrs: nounwind
define fastcc <256 x i64> @urem_sv_v256i64(i64 %x, <256 x i64> %y) {
; CHECK-LABEL: urem_sv_v256i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vdivu.l %v1, %s0, %v0
; CHECK-NEXT:    vmuls.l %v0, %v1, %v0
; CHECK-NEXT:    vsubs.l %v0, %s0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %xins = insertelement <256 x i64> undef, i64 %x, i32 0
  %vx = shufflevector <256 x i64> %xins, <256 x i64> undef, <256 x i32> zeroinitializer
  %z = urem <256 x i64> %vx, %y
  ret <256 x i64> %z
}

; Function Attrs: nounwind
define fastcc <256 x i64> @urem_vs_v256i64(<256 x i64> %x, i64 %y) {
; CHECK-LABEL: urem_vs_v256i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s1, 256
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    vdivu.l %v1, %v0, %s0
; CHECK-NEXT:    vmuls.l %v1, %s0, %v1
; CHECK-NEXT:    vsubs.l %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %yins = insertelement <256 x i64> undef, i64 %y, i32 0
  %vy = shufflevector <256 x i64> %yins, <256 x i64> undef, <256 x i32> zeroinitializer
  %z = urem <256 x i64> %x, %vy
  ret <256 x i64> %z
}

; <128 x i64>
; We expect this to be widened.

; Function Attrs: nounwind
define fastcc <128 x i64> @urem_vv_v128i64(<128 x i64> %x, <128 x i64> %y) {
; CHECK-LABEL: urem_vv_v128i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 128
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vdivu.l %v2, %v0, %v1
; CHECK-NEXT:    vmuls.l %v1, %v2, %v1
; CHECK-NEXT:    vsubs.l %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %z = urem <128 x i64> %x, %y
  ret <128 x i64> %z
}

; <256 x i16>
; We expect promotion.

; Function Attrs: nounwind
define fastcc <256 x i16> @urem_vv_v256i16(<256 x i16> %x, <256 x i16> %y) {
; CHECK-LABEL: urem_vv_v256i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lea %s1, 65535
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvand.lo %v1, %s1, %v1
; CHECK-NEXT:    pvand.lo %v0, %s1, %v0
; CHECK-NEXT:    vdivu.w %v2, %v0, %v1
; CHECK-NEXT:    vmuls.w.sx %v1, %v2, %v1
; CHECK-NEXT:    vsubs.w.sx %v0, %v0, %v1
; CHECK-NEXT:    b.l.t (, %s10)
  %z = urem <256 x i16> %x, %y
  ret <256 x i16> %z
}

; <128 x i16>
; We expect this to be scalarized (for now).

; Function Attrs: nounwind
define fastcc <128 x i16> @urem_vv_v128i16(<128 x i16> %x, <128 x i16> %y) {
; CHECK-LABEL: urem_vv_v128i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -496(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB8_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    st %s18, 544(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s19, 552(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s20, 560(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s21, 568(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s22, 576(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s23, 584(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s24, 592(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s25, 600(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s26, 608(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s27, 616(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s28, 624(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s29, 632(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s30, 640(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s31, 648(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s32, 656(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    st %s33, 664(, %s11) # 8-byte Folded Spill
; CHECK-NEXT:    and %s7, %s7, (48)0
; CHECK-NEXT:    and %s6, %s6, (48)0
; CHECK-NEXT:    and %s5, %s5, (48)0
; CHECK-NEXT:    and %s4, %s4, (48)0
; CHECK-NEXT:    and %s3, %s3, (48)0
; CHECK-NEXT:    and %s2, %s2, (48)0
; CHECK-NEXT:    and %s1, %s1, (48)0
; CHECK-NEXT:    ld2b.zx %s34, 2096(, %s11)
; CHECK-NEXT:    ld2b.zx %s35, 2088(, %s11)
; CHECK-NEXT:    ld2b.zx %s36, 2080(, %s11)
; CHECK-NEXT:    ld2b.zx %s37, 2072(, %s11)
; CHECK-NEXT:    ld2b.zx %s38, 2064(, %s11)
; CHECK-NEXT:    ld2b.zx %s39, 2056(, %s11)
; CHECK-NEXT:    ld2b.zx %s40, 2048(, %s11)
; CHECK-NEXT:    ld2b.zx %s41, 2040(, %s11)
; CHECK-NEXT:    ld2b.zx %s42, 2032(, %s11)
; CHECK-NEXT:    ld2b.zx %s43, 2024(, %s11)
; CHECK-NEXT:    ld2b.zx %s44, 2016(, %s11)
; CHECK-NEXT:    ld2b.zx %s45, 2008(, %s11)
; CHECK-NEXT:    ld2b.zx %s46, 2000(, %s11)
; CHECK-NEXT:    ld2b.zx %s47, 1992(, %s11)
; CHECK-NEXT:    ld2b.zx %s48, 1984(, %s11)
; CHECK-NEXT:    ld2b.zx %s49, 1976(, %s11)
; CHECK-NEXT:    ld2b.zx %s50, 1968(, %s11)
; CHECK-NEXT:    ld2b.zx %s51, 1960(, %s11)
; CHECK-NEXT:    ld2b.zx %s52, 1952(, %s11)
; CHECK-NEXT:    ld2b.zx %s53, 1944(, %s11)
; CHECK-NEXT:    ld2b.zx %s54, 1936(, %s11)
; CHECK-NEXT:    ld2b.zx %s55, 1928(, %s11)
; CHECK-NEXT:    ld2b.zx %s56, 1920(, %s11)
; CHECK-NEXT:    ld2b.zx %s57, 1912(, %s11)
; CHECK-NEXT:    ld2b.zx %s58, 1904(, %s11)
; CHECK-NEXT:    ld2b.zx %s59, 1896(, %s11)
; CHECK-NEXT:    ld2b.zx %s60, 1888(, %s11)
; CHECK-NEXT:    ld2b.zx %s61, 1880(, %s11)
; CHECK-NEXT:    ld2b.zx %s62, 1872(, %s11)
; CHECK-NEXT:    ld2b.zx %s63, 1864(, %s11)
; CHECK-NEXT:    ld2b.zx %s18, 1856(, %s11)
; CHECK-NEXT:    ld2b.zx %s19, 1848(, %s11)
; CHECK-NEXT:    ld2b.zx %s20, 1840(, %s11)
; CHECK-NEXT:    ld2b.zx %s21, 1832(, %s11)
; CHECK-NEXT:    ld2b.zx %s22, 1824(, %s11)
; CHECK-NEXT:    ld2b.zx %s23, 1816(, %s11)
; CHECK-NEXT:    ld2b.zx %s24, 1808(, %s11)
; CHECK-NEXT:    ld2b.zx %s25, 1800(, %s11)
; CHECK-NEXT:    ld2b.zx %s26, 1792(, %s11)
; CHECK-NEXT:    ld2b.zx %s27, 1784(, %s11)
; CHECK-NEXT:    ld2b.zx %s28, 1776(, %s11)
; CHECK-NEXT:    ld2b.zx %s29, 1704(, %s11)
; CHECK-NEXT:    ld2b.zx %s30, 1768(, %s11)
; CHECK-NEXT:    ld2b.zx %s31, 1760(, %s11)
; CHECK-NEXT:    ld2b.zx %s32, 1712(, %s11)
; CHECK-NEXT:    divu.w %s33, %s1, %s29
; CHECK-NEXT:    muls.w.sx %s29, %s33, %s29
; CHECK-NEXT:    ld2b.zx %s33, 1720(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s1, %s29
; CHECK-NEXT:    stl %s1, 492(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s32
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s32
; CHECK-NEXT:    ld2b.zx %s29, 1728(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 488(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s33
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s33
; CHECK-NEXT:    ld2b.zx %s2, 1736(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 484(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s29
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s29
; CHECK-NEXT:    ld2b.zx %s3, 1744(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 480(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s5, %s2
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s2
; CHECK-NEXT:    ld2b.zx %s2, 1752(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s5, %s1
; CHECK-NEXT:    stl %s1, 476(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s6, %s3
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 736(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s6, %s1
; CHECK-NEXT:    stl %s1, 472(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s7, %s2
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s2
; CHECK-NEXT:    ld2b.zx %s2, 744(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s7, %s1
; CHECK-NEXT:    stl %s1, 468(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s31
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s31
; CHECK-NEXT:    ld2b.zx %s4, 752(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 464(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s30
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s30
; CHECK-NEXT:    ld2b.zx %s3, 760(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 460(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s28
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s28
; CHECK-NEXT:    ld2b.zx %s2, 768(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 456(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s27
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s27
; CHECK-NEXT:    ld2b.zx %s4, 776(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 452(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s26
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s26
; CHECK-NEXT:    ld2b.zx %s3, 784(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 448(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s25
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s25
; CHECK-NEXT:    ld2b.zx %s2, 792(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 444(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s24
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s24
; CHECK-NEXT:    ld2b.zx %s4, 800(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 440(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s23
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s23
; CHECK-NEXT:    ld2b.zx %s3, 808(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 436(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s22
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s22
; CHECK-NEXT:    ld2b.zx %s2, 816(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 432(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s21
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s21
; CHECK-NEXT:    ld2b.zx %s4, 824(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 428(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s20
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s20
; CHECK-NEXT:    ld2b.zx %s3, 832(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 424(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s19
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s19
; CHECK-NEXT:    ld2b.zx %s2, 840(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 420(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s18
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s18
; CHECK-NEXT:    ld2b.zx %s4, 848(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 416(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s63
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s63
; CHECK-NEXT:    ld2b.zx %s3, 856(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 412(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s62
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s62
; CHECK-NEXT:    ld2b.zx %s2, 864(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 408(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s61
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s61
; CHECK-NEXT:    ld2b.zx %s4, 872(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 404(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s60
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s60
; CHECK-NEXT:    ld2b.zx %s3, 880(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 400(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s59
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s59
; CHECK-NEXT:    ld2b.zx %s2, 888(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 396(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s58
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s58
; CHECK-NEXT:    ld2b.zx %s4, 896(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 392(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s57
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s57
; CHECK-NEXT:    ld2b.zx %s3, 904(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 388(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s56
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s56
; CHECK-NEXT:    ld2b.zx %s2, 912(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 384(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s55
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s55
; CHECK-NEXT:    ld2b.zx %s4, 920(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 380(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s54
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s54
; CHECK-NEXT:    ld2b.zx %s3, 928(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 376(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s53
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s53
; CHECK-NEXT:    ld2b.zx %s2, 936(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 372(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s52
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s52
; CHECK-NEXT:    ld2b.zx %s4, 944(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 368(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s51
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s51
; CHECK-NEXT:    ld2b.zx %s3, 952(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 364(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s50
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s50
; CHECK-NEXT:    ld2b.zx %s2, 960(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 360(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s49
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s49
; CHECK-NEXT:    ld2b.zx %s4, 968(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 356(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s48
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s48
; CHECK-NEXT:    ld2b.zx %s3, 976(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 352(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s47
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s47
; CHECK-NEXT:    ld2b.zx %s2, 984(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 348(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s46
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s46
; CHECK-NEXT:    ld2b.zx %s4, 992(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 344(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s45
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s45
; CHECK-NEXT:    ld2b.zx %s3, 1000(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 340(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s44
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s44
; CHECK-NEXT:    ld2b.zx %s2, 1008(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 336(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s43
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s43
; CHECK-NEXT:    ld2b.zx %s4, 1016(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 332(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s42
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s42
; CHECK-NEXT:    ld2b.zx %s3, 1024(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 328(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s41
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s41
; CHECK-NEXT:    ld2b.zx %s2, 1032(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 324(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s40
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s40
; CHECK-NEXT:    ld2b.zx %s4, 1040(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 320(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s39
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s39
; CHECK-NEXT:    ld2b.zx %s3, 1048(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 316(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s38
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s38
; CHECK-NEXT:    ld2b.zx %s2, 1056(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 312(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s37
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s37
; CHECK-NEXT:    ld2b.zx %s4, 1064(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 308(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s2, %s36
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s36
; CHECK-NEXT:    ld2b.zx %s3, 1072(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s2, %s1
; CHECK-NEXT:    stl %s1, 304(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s4, %s35
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s35
; CHECK-NEXT:    ld2b.zx %s2, 2104(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s4, %s1
; CHECK-NEXT:    stl %s1, 300(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s1, %s3, %s34
; CHECK-NEXT:    muls.w.sx %s1, %s1, %s34
; CHECK-NEXT:    ld2b.zx %s4, 1080(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 296(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2112(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1088(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 292(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2120(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1096(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 288(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2128(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1104(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 284(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2136(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1112(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 280(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2144(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1120(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 276(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2152(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1128(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 272(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2160(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1136(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 268(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2168(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1144(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 264(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2176(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1152(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 260(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2184(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1160(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 256(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2192(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1168(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 252(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2200(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1176(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 248(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2208(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1184(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 244(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2216(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1192(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 240(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2224(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1200(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 236(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2232(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1208(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 232(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2240(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1216(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 228(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2248(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1224(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 224(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2256(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1232(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 220(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2264(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1240(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 216(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2272(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1248(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 212(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2280(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1256(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 208(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2288(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1264(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 204(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2296(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1272(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 200(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2304(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1280(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 196(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2312(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1288(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 192(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2320(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1296(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s2, %s4, %s2
; CHECK-NEXT:    stl %s2, 188(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2328(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1304(, %s11)
; CHECK-NEXT:    subs.w.sx %s1, %s3, %s1
; CHECK-NEXT:    stl %s1, 184(, %s11) # 4-byte Folded Spill
; CHECK-NEXT:    ld2b.zx %s1, 2336(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1312(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s61, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2344(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1320(, %s11)
; CHECK-NEXT:    subs.w.sx %s60, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2352(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1328(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s59, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2360(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1336(, %s11)
; CHECK-NEXT:    subs.w.sx %s58, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2368(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1344(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s57, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2376(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1352(, %s11)
; CHECK-NEXT:    subs.w.sx %s56, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2384(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1360(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s55, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2392(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1368(, %s11)
; CHECK-NEXT:    subs.w.sx %s54, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2400(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1376(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s53, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2408(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1384(, %s11)
; CHECK-NEXT:    subs.w.sx %s52, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2416(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1392(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s51, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2424(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1400(, %s11)
; CHECK-NEXT:    subs.w.sx %s50, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2432(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1408(, %s11)
; CHECK-NEXT:    divu.w %s5, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s5, %s2
; CHECK-NEXT:    subs.w.sx %s49, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2440(, %s11)
; CHECK-NEXT:    ld2b.zx %s4, 1416(, %s11)
; CHECK-NEXT:    subs.w.sx %s48, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2448(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1424(, %s11)
; CHECK-NEXT:    divu.w %s24, %s4, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s24, %s2
; CHECK-NEXT:    subs.w.sx %s47, %s4, %s2
; CHECK-NEXT:    divu.w %s2, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s2, %s1
; CHECK-NEXT:    ld2b.zx %s2, 2456(, %s11)
; CHECK-NEXT:    ld2b.zx %s24, 1432(, %s11)
; CHECK-NEXT:    subs.w.sx %s46, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s1, 2464(, %s11)
; CHECK-NEXT:    ld2b.zx %s3, 1440(, %s11)
; CHECK-NEXT:    divu.w %s26, %s24, %s2
; CHECK-NEXT:    muls.w.sx %s2, %s26, %s2
; CHECK-NEXT:    subs.w.sx %s45, %s24, %s2
; CHECK-NEXT:    divu.w %s24, %s3, %s1
; CHECK-NEXT:    muls.w.sx %s1, %s24, %s1
; CHECK-NEXT:    ld2b.zx %s24, 2472(, %s11)
; CHECK-NEXT:    ld2b.zx %s26, 1448(, %s11)
; CHECK-NEXT:    subs.w.sx %s44, %s3, %s1
; CHECK-NEXT:    ld2b.zx %s3, 2480(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1456(, %s11)
; CHECK-NEXT:    divu.w %s28, %s26, %s24
; CHECK-NEXT:    muls.w.sx %s24, %s28, %s24
; CHECK-NEXT:    subs.w.sx %s24, %s26, %s24
; CHECK-NEXT:    divu.w %s26, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s26, %s3
; CHECK-NEXT:    ld2b.zx %s26, 2488(, %s11)
; CHECK-NEXT:    ld2b.zx %s28, 1464(, %s11)
; CHECK-NEXT:    subs.w.sx %s43, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2496(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1472(, %s11)
; CHECK-NEXT:    divu.w %s30, %s28, %s26
; CHECK-NEXT:    muls.w.sx %s26, %s30, %s26
; CHECK-NEXT:    subs.w.sx %s26, %s28, %s26
; CHECK-NEXT:    divu.w %s28, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s28, %s3
; CHECK-NEXT:    ld2b.zx %s28, 2504(, %s11)
; CHECK-NEXT:    ld2b.zx %s30, 1480(, %s11)
; CHECK-NEXT:    subs.w.sx %s42, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2512(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1488(, %s11)
; CHECK-NEXT:    divu.w %s32, %s30, %s28
; CHECK-NEXT:    muls.w.sx %s28, %s32, %s28
; CHECK-NEXT:    subs.w.sx %s28, %s30, %s28
; CHECK-NEXT:    divu.w %s30, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s30, %s3
; CHECK-NEXT:    ld2b.zx %s30, 2520(, %s11)
; CHECK-NEXT:    ld2b.zx %s32, 1496(, %s11)
; CHECK-NEXT:    subs.w.sx %s41, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2528(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1504(, %s11)
; CHECK-NEXT:    divu.w %s33, %s32, %s30
; CHECK-NEXT:    muls.w.sx %s30, %s33, %s30
; CHECK-NEXT:    subs.w.sx %s30, %s32, %s30
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2536(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1512(, %s11)
; CHECK-NEXT:    subs.w.sx %s40, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2544(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1520(, %s11)
; CHECK-NEXT:    divu.w %s31, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s31, %s31, %s32
; CHECK-NEXT:    subs.w.sx %s31, %s33, %s31
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2552(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1528(, %s11)
; CHECK-NEXT:    subs.w.sx %s39, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2560(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1536(, %s11)
; CHECK-NEXT:    divu.w %s29, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s29, %s29, %s32
; CHECK-NEXT:    subs.w.sx %s29, %s33, %s29
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2568(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1544(, %s11)
; CHECK-NEXT:    subs.w.sx %s38, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2576(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1552(, %s11)
; CHECK-NEXT:    divu.w %s27, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s27, %s27, %s32
; CHECK-NEXT:    subs.w.sx %s27, %s33, %s27
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2584(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1560(, %s11)
; CHECK-NEXT:    subs.w.sx %s37, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2592(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1568(, %s11)
; CHECK-NEXT:    divu.w %s25, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s25, %s25, %s32
; CHECK-NEXT:    subs.w.sx %s25, %s33, %s25
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2600(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1576(, %s11)
; CHECK-NEXT:    subs.w.sx %s36, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2608(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1584(, %s11)
; CHECK-NEXT:    divu.w %s23, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s23, %s23, %s32
; CHECK-NEXT:    subs.w.sx %s23, %s33, %s23
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2616(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1592(, %s11)
; CHECK-NEXT:    subs.w.sx %s35, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2624(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1600(, %s11)
; CHECK-NEXT:    divu.w %s22, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s22, %s22, %s32
; CHECK-NEXT:    subs.w.sx %s22, %s33, %s22
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2632(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1608(, %s11)
; CHECK-NEXT:    subs.w.sx %s34, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2640(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1616(, %s11)
; CHECK-NEXT:    divu.w %s21, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s21, %s21, %s32
; CHECK-NEXT:    subs.w.sx %s21, %s33, %s21
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2648(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1624(, %s11)
; CHECK-NEXT:    subs.w.sx %s7, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2656(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1632(, %s11)
; CHECK-NEXT:    divu.w %s20, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s20, %s20, %s32
; CHECK-NEXT:    subs.w.sx %s20, %s33, %s20
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2664(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1640(, %s11)
; CHECK-NEXT:    subs.w.sx %s6, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2672(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1648(, %s11)
; CHECK-NEXT:    divu.w %s19, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s19, %s19, %s32
; CHECK-NEXT:    subs.w.sx %s19, %s33, %s19
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2680(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1656(, %s11)
; CHECK-NEXT:    subs.w.sx %s5, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2688(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1664(, %s11)
; CHECK-NEXT:    divu.w %s18, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s18, %s18, %s32
; CHECK-NEXT:    subs.w.sx %s18, %s33, %s18
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2696(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1672(, %s11)
; CHECK-NEXT:    subs.w.sx %s4, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2704(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1680(, %s11)
; CHECK-NEXT:    divu.w %s63, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s63, %s63, %s32
; CHECK-NEXT:    subs.w.sx %s63, %s33, %s63
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    ld2b.zx %s32, 2712(, %s11)
; CHECK-NEXT:    ld2b.zx %s33, 1688(, %s11)
; CHECK-NEXT:    subs.w.sx %s2, %s1, %s3
; CHECK-NEXT:    ld2b.zx %s3, 2720(, %s11)
; CHECK-NEXT:    ld2b.zx %s1, 1696(, %s11)
; CHECK-NEXT:    divu.w %s62, %s33, %s32
; CHECK-NEXT:    muls.w.sx %s62, %s62, %s32
; CHECK-NEXT:    subs.w.sx %s62, %s33, %s62
; CHECK-NEXT:    divu.w %s32, %s1, %s3
; CHECK-NEXT:    muls.w.sx %s3, %s32, %s3
; CHECK-NEXT:    subs.w.sx %s1, %s1, %s3
; CHECK-NEXT:    st2b %s1, 254(, %s0)
; CHECK-NEXT:    st2b %s62, 252(, %s0)
; CHECK-NEXT:    st2b %s2, 250(, %s0)
; CHECK-NEXT:    st2b %s63, 248(, %s0)
; CHECK-NEXT:    st2b %s4, 246(, %s0)
; CHECK-NEXT:    st2b %s18, 244(, %s0)
; CHECK-NEXT:    st2b %s5, 242(, %s0)
; CHECK-NEXT:    st2b %s19, 240(, %s0)
; CHECK-NEXT:    st2b %s6, 238(, %s0)
; CHECK-NEXT:    st2b %s20, 236(, %s0)
; CHECK-NEXT:    st2b %s7, 234(, %s0)
; CHECK-NEXT:    st2b %s21, 232(, %s0)
; CHECK-NEXT:    st2b %s34, 230(, %s0)
; CHECK-NEXT:    st2b %s22, 228(, %s0)
; CHECK-NEXT:    st2b %s35, 226(, %s0)
; CHECK-NEXT:    st2b %s23, 224(, %s0)
; CHECK-NEXT:    st2b %s36, 222(, %s0)
; CHECK-NEXT:    st2b %s25, 220(, %s0)
; CHECK-NEXT:    st2b %s37, 218(, %s0)
; CHECK-NEXT:    st2b %s27, 216(, %s0)
; CHECK-NEXT:    st2b %s38, 214(, %s0)
; CHECK-NEXT:    st2b %s29, 212(, %s0)
; CHECK-NEXT:    st2b %s39, 210(, %s0)
; CHECK-NEXT:    st2b %s31, 208(, %s0)
; CHECK-NEXT:    st2b %s40, 206(, %s0)
; CHECK-NEXT:    st2b %s30, 204(, %s0)
; CHECK-NEXT:    st2b %s41, 202(, %s0)
; CHECK-NEXT:    st2b %s28, 200(, %s0)
; CHECK-NEXT:    st2b %s42, 198(, %s0)
; CHECK-NEXT:    st2b %s26, 196(, %s0)
; CHECK-NEXT:    st2b %s43, 194(, %s0)
; CHECK-NEXT:    st2b %s24, 192(, %s0)
; CHECK-NEXT:    st2b %s44, 190(, %s0)
; CHECK-NEXT:    st2b %s45, 188(, %s0)
; CHECK-NEXT:    st2b %s46, 186(, %s0)
; CHECK-NEXT:    st2b %s47, 184(, %s0)
; CHECK-NEXT:    st2b %s48, 182(, %s0)
; CHECK-NEXT:    st2b %s49, 180(, %s0)
; CHECK-NEXT:    st2b %s50, 178(, %s0)
; CHECK-NEXT:    st2b %s51, 176(, %s0)
; CHECK-NEXT:    st2b %s52, 174(, %s0)
; CHECK-NEXT:    st2b %s53, 172(, %s0)
; CHECK-NEXT:    st2b %s54, 170(, %s0)
; CHECK-NEXT:    st2b %s55, 168(, %s0)
; CHECK-NEXT:    st2b %s56, 166(, %s0)
; CHECK-NEXT:    st2b %s57, 164(, %s0)
; CHECK-NEXT:    st2b %s58, 162(, %s0)
; CHECK-NEXT:    st2b %s59, 160(, %s0)
; CHECK-NEXT:    st2b %s60, 158(, %s0)
; CHECK-NEXT:    st2b %s61, 156(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 184(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 154(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 188(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 152(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 192(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 150(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 196(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 148(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 200(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 146(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 204(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 144(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 208(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 142(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 212(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 140(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 216(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 138(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 220(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 136(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 224(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 134(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 228(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 132(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 232(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 130(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 236(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 128(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 240(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 126(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 244(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 124(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 248(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 122(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 252(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 120(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 256(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 118(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 260(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 116(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 264(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 114(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 268(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 112(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 272(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 110(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 276(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 108(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 280(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 106(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 284(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 104(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 288(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 102(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 292(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 100(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 296(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 98(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 300(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 96(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 304(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 94(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 308(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 92(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 312(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 90(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 316(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 88(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 320(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 86(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 324(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 84(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 328(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 82(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 332(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 80(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 336(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 78(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 340(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 76(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 344(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 74(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 348(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 72(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 352(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 70(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 356(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 68(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 360(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 66(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 364(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 64(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 368(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 62(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 372(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 60(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 376(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 58(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 380(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 56(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 384(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 54(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 388(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 52(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 392(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 50(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 396(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 48(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 400(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 46(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 404(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 44(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 408(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 42(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 412(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 40(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 416(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 38(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 420(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 36(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 424(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 34(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 428(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 32(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 432(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 30(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 436(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 28(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 440(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 26(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 444(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 24(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 448(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 22(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 452(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 20(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 456(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 18(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 460(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 16(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 464(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 14(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 468(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 12(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 472(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 10(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 476(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 8(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 480(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 6(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 484(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 4(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 488(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, 2(, %s0)
; CHECK-NEXT:    ldl.sx %s1, 492(, %s11) # 4-byte Folded Reload
; CHECK-NEXT:    st2b %s1, (, %s0)
; CHECK-NEXT:    ld %s33, 664(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s32, 656(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s31, 648(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s30, 640(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s29, 632(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s28, 624(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s27, 616(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s26, 608(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s25, 600(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s24, 592(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s23, 584(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s22, 576(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s21, 568(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s20, 560(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s19, 552(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s18, 544(, %s11) # 8-byte Folded Reload
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
  %z = urem <128 x i16> %x, %y
  ret <128 x i16> %z
}

