; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

declare <256 x i64> @llvm.ctpop.v256i64(<256 x i64>)
declare <256 x i32> @llvm.ctpop.v256i32(<256 x i32>)
declare <256 x i16> @llvm.ctpop.v256i16(<256 x i16>)

define fastcc <256 x i64> @vec_ctpopv256i64(<256 x i64> %a) {
; CHECK-LABEL: vec_ctpopv256i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vpcnt %v0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call <256 x i64> @llvm.ctpop.v256i64(<256 x i64> %a)
  ret <256 x i64> %r
}

define fastcc <256 x i32> @vec_ctpopv256i32(<256 x i32> %a) {
; CHECK-LABEL: vec_ctpopv256i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvpcnt.lo %v0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call <256 x i32> @llvm.ctpop.v256i32(<256 x i32> %a)
  ret <256 x i32> %r
}

define fastcc <256 x i16> @vec_ctpopv256i16(<256 x i16> %a) {
; CHECK-LABEL: vec_ctpopv256i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lea %s1, 65535
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    pvand.lo %v0, %s1, %v0
; CHECK-NEXT:    pvpcnt.lo %v0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call <256 x i16> @llvm.ctpop.v256i16(<256 x i16> %a)
  ret <256 x i16> %r
}


