; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=ve-unknown-unknown -mattr=+vpu | FileCheck %s

define fastcc <1 x float> @vec_fptrunc_v1_double_to_float(<1 x double> %a) {
; CHECK-LABEL: vec_fptrunc_v1_double_to_float:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvt.s.d %s0, %s0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = fptrunc <1 x double> %a to <1 x float>
  ret <1 x float> %r
}

define fastcc <256 x float> @vec_fptrunc_v256_double_to_float(<256 x double> %a) {
; CHECK-LABEL: vec_fptrunc_v256_double_to_float:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 256
; CHECK-NEXT:    lvl %s0
; CHECK-NEXT:    vcvt.s.d %v0, %v0
; CHECK-NEXT:    b.l.t (, %s10)
  %r = fptrunc <256 x double> %a to <256 x float>
  ret <256 x float> %r
}

