; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O0 --march=ve -mattr=+vpu %s -o=/dev/stdout | FileCheck %s

define fastcc i1 @test_reduce_and(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n) {
; FIXME: The generated code is incorrect!
; CHECK-LABEL: test_reduce_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    or %s2, 0, %s1
; CHECK-NEXT:    andm %vm1, %vm1, %vm2
; CHECK-NEXT:    lvl %s2
; CHECK-NEXT:    pcvm %s1, %vm1
; CHECK-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-NEXT:    cmpu.w %s2, %s1, %s2
; CHECK-NEXT:    # implicit-def: $sx1
; CHECK-NEXT:    or %s1, 0, %s2
; CHECK-NEXT:    ldz %s1, %s1
; CHECK-NEXT:    srl %s1, %s1, 6
; CHECK-NEXT:    or %s2, 0, %s1
; CHECK-NEXT:    # implicit-def: $sx1
; CHECK-NEXT:    or %s1, 0, %s2
; CHECK-NEXT:    and %s0, %s0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.and.v256i1(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_or(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n) {
; CHECK-LABEL: test_reduce_or:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-NEXT:    andm %vm1, %vm1, %vm2
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    pcvm %s1, %vm1
; CHECK-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-NEXT:    cmpu.w %s2, 0, %s1
; CHECK-NEXT:    # implicit-def: $sx1
; CHECK-NEXT:    or %s1, 0, %s2
; CHECK-NEXT:    srl %s1, %s1, 31
; CHECK-NEXT:    or %s2, 0, %s1
; CHECK-NEXT:    # implicit-def: $sx1
; CHECK-NEXT:    or %s1, 0, %s2
; CHECK-NEXT:    or %s0, %s0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.or.v256i1(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n)
  ret i1 %r
}

define fastcc i1 @test_reduce_xor(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n) {
; CHECK-LABEL: test_reduce_xor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    # kill: def $sw1 killed $sw1 killed $sx1
; CHECK-NEXT:    andm %vm1, %vm1, %vm2
; CHECK-NEXT:    lvl %s1
; CHECK-NEXT:    pcvm %s1, %vm1
; CHECK-NEXT:    and %s1, 1, %s1
; CHECK-NEXT:    xor %s0, %s0, %s1
; CHECK-NEXT:    b.l.t (, %s10)
  %r = call i1 @llvm.vp.reduce.xor.v256i1(i1 %s, <256 x i1> %v, <256 x i1> %m, i32 %n)
  ret i1 %r
}

declare i1 @llvm.vp.reduce.and.v256i1(i1 %s, <256 x i1>, <256 x i1>, i32)
declare i1 @llvm.vp.reduce.xor.v256i1(i1 %s, <256 x i1>, <256 x i1>, i32)
declare i1 @llvm.vp.reduce.or.v256i1(i1 %s, <256 x i1>, <256 x i1>, i32)
