; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=ve | FileCheck %s
; RUN: llc < %s -mtriple=ve -relocation-model=pic \
; RUN:     | FileCheck -check-prefix=PIC %s

; Test CFI directive emission for VE prologue/epilogue.

declare void @external()

; Non-leaf function: should have CFI for FP/LR save/restore.
define void @non_leaf() #0 {
; CHECK-LABEL: non_leaf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    .cfi_offset %s9, 0
; CHECK-NEXT:    .cfi_offset %s10, 8
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    .cfi_def_cfa_register %s9
; CHECK-NEXT:    lea %s11, -240(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    lea %s0, external@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, external@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    .cfi_def_cfa %s11, 0
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    .cfi_restore %s10
; CHECK-NEXT:    .cfi_restore %s9
; CHECK-NEXT:    b.l.t (, %s10)
;
; PIC-LABEL: non_leaf:
; PIC:       # %bb.0:
; PIC-NEXT:    st %s9, (, %s11)
; PIC-NEXT:    st %s10, 8(, %s11)
; PIC-NEXT:    st %s15, 24(, %s11)
; PIC-NEXT:    st %s16, 32(, %s11)
; PIC-NEXT:    .cfi_offset %s9, 0
; PIC-NEXT:    .cfi_offset %s10, 8
; PIC-NEXT:    .cfi_offset %s15, 24
; PIC-NEXT:    .cfi_offset %s16, 32
; PIC-NEXT:    or %s9, 0, %s11
; PIC-NEXT:    .cfi_def_cfa_register %s9
; PIC-NEXT:    lea %s11, -240(, %s11)
; PIC-NEXT:    brge.l.t %s11, %s8, .LBB0_2
; PIC-NEXT:  # %bb.1:
; PIC-NEXT:    ld %s61, 24(, %s14)
; PIC-NEXT:    or %s62, 0, %s0
; PIC-NEXT:    lea %s63, 315
; PIC-NEXT:    shm.l %s63, (%s61)
; PIC-NEXT:    shm.l %s8, 8(%s61)
; PIC-NEXT:    shm.l %s11, 16(%s61)
; PIC-NEXT:    monc
; PIC-NEXT:    or %s0, 0, %s62
; PIC-NEXT:  .LBB0_2:
; PIC-NEXT:    lea %s15, _GLOBAL_OFFSET_TABLE_@pc_lo(-24)
; PIC-NEXT:    and %s15, %s15, (32)0
; PIC-NEXT:    sic %s16
; PIC-NEXT:    lea.sl %s15, _GLOBAL_OFFSET_TABLE_@pc_hi(%s16, %s15)
; PIC-NEXT:    lea %s12, external@plt_lo(-24)
; PIC-NEXT:    and %s12, %s12, (32)0
; PIC-NEXT:    sic %s16
; PIC-NEXT:    lea.sl %s12, external@plt_hi(%s16, %s12)
; PIC-NEXT:    bsic %s10, (, %s12)
; PIC-NEXT:    or %s11, 0, %s9
; PIC-NEXT:    .cfi_def_cfa %s11, 0
; PIC-NEXT:    ld %s16, 32(, %s11)
; PIC-NEXT:    ld %s15, 24(, %s11)
; PIC-NEXT:    ld %s10, 8(, %s11)
; PIC-NEXT:    ld %s9, (, %s11)
; PIC-NEXT:    .cfi_restore %s16
; PIC-NEXT:    .cfi_restore %s15
; PIC-NEXT:    .cfi_restore %s10
; PIC-NEXT:    .cfi_restore %s9
; PIC-NEXT:    b.l.t (, %s10)
  call void @external()
  ret void
}

; Function with CSR usage: value live across call needs callee-saved register.
define i64 @csr_usage(i64 %a) #0 {
; CHECK-LABEL: csr_usage:
; CHECK:       # %bb.0:
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    .cfi_offset %s9, 0
; CHECK-NEXT:    .cfi_offset %s10, 8
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    .cfi_def_cfa_register %s9
; CHECK-NEXT:    lea %s11, -240(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB1_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB1_2:
; CHECK-NEXT:    st %s18, 48(, %s9) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset %s18, 48
; CHECK-NEXT:    or %s18, 0, %s0
; CHECK-NEXT:    lea %s0, external@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, external@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    or %s0, 0, %s18
; CHECK-NEXT:    ld %s18, 48(, %s9) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore %s18
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    .cfi_def_cfa %s11, 0
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    .cfi_restore %s10
; CHECK-NEXT:    .cfi_restore %s9
; CHECK-NEXT:    b.l.t (, %s10)
;
; PIC-LABEL: csr_usage:
; PIC:       # %bb.0:
; PIC-NEXT:    st %s9, (, %s11)
; PIC-NEXT:    st %s10, 8(, %s11)
; PIC-NEXT:    st %s15, 24(, %s11)
; PIC-NEXT:    st %s16, 32(, %s11)
; PIC-NEXT:    .cfi_offset %s9, 0
; PIC-NEXT:    .cfi_offset %s10, 8
; PIC-NEXT:    .cfi_offset %s15, 24
; PIC-NEXT:    .cfi_offset %s16, 32
; PIC-NEXT:    or %s9, 0, %s11
; PIC-NEXT:    .cfi_def_cfa_register %s9
; PIC-NEXT:    lea %s11, -240(, %s11)
; PIC-NEXT:    brge.l.t %s11, %s8, .LBB1_2
; PIC-NEXT:  # %bb.1:
; PIC-NEXT:    ld %s61, 24(, %s14)
; PIC-NEXT:    or %s62, 0, %s0
; PIC-NEXT:    lea %s63, 315
; PIC-NEXT:    shm.l %s63, (%s61)
; PIC-NEXT:    shm.l %s8, 8(%s61)
; PIC-NEXT:    shm.l %s11, 16(%s61)
; PIC-NEXT:    monc
; PIC-NEXT:    or %s0, 0, %s62
; PIC-NEXT:  .LBB1_2:
; PIC-NEXT:    st %s18, 48(, %s9) # 8-byte Folded Spill
; PIC-NEXT:    .cfi_offset %s18, 48
; PIC-NEXT:    or %s18, 0, %s0
; PIC-NEXT:    lea %s15, _GLOBAL_OFFSET_TABLE_@pc_lo(-24)
; PIC-NEXT:    and %s15, %s15, (32)0
; PIC-NEXT:    sic %s16
; PIC-NEXT:    lea.sl %s15, _GLOBAL_OFFSET_TABLE_@pc_hi(%s16, %s15)
; PIC-NEXT:    lea %s12, external@plt_lo(-24)
; PIC-NEXT:    and %s12, %s12, (32)0
; PIC-NEXT:    sic %s16
; PIC-NEXT:    lea.sl %s12, external@plt_hi(%s16, %s12)
; PIC-NEXT:    bsic %s10, (, %s12)
; PIC-NEXT:    or %s0, 0, %s18
; PIC-NEXT:    ld %s18, 48(, %s9) # 8-byte Folded Reload
; PIC-NEXT:    .cfi_restore %s18
; PIC-NEXT:    or %s11, 0, %s9
; PIC-NEXT:    .cfi_def_cfa %s11, 0
; PIC-NEXT:    ld %s16, 32(, %s11)
; PIC-NEXT:    ld %s15, 24(, %s11)
; PIC-NEXT:    ld %s10, 8(, %s11)
; PIC-NEXT:    ld %s9, (, %s11)
; PIC-NEXT:    .cfi_restore %s16
; PIC-NEXT:    .cfi_restore %s15
; PIC-NEXT:    .cfi_restore %s10
; PIC-NEXT:    .cfi_restore %s9
; PIC-NEXT:    b.l.t (, %s10)
  call void @external()
  ret i64 %a
}

; Leaf function: no CFI expected.
define i64 @leaf(i64 %a) {
; CHECK-LABEL: leaf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lea %s0, 1(, %s0)
; CHECK-NEXT:    b.l.t (, %s10)
;
; PIC-LABEL: leaf:
; PIC:       # %bb.0:
; PIC-NEXT:    lea %s0, 1(, %s0)
; PIC-NEXT:    b.l.t (, %s10)
  %b = add i64 %a, 1
  ret i64 %b
}

attributes #0 = { uwtable }
