; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=ve < %s | FileCheck %s

declare void @foo(ptr %p)
declare void @bar(ptr %p)
declare dso_local i32 @__gxx_personality_v0(...)

; Test cleanup landingpad with resume (_Unwind_Resume)
define void @cleanup(ptr %p) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: cleanup:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    .cfi_offset %s9, 0
; CHECK-NEXT:    .cfi_offset %s10, 8
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    .cfi_def_cfa_register %s9
; CHECK-NEXT:    lea %s11, -240(, %s11)
; CHECK-NEXT:    brge.l %s11, %s8, .LBB0_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB0_4: # %entry
; CHECK-NEXT:    st %s18, 48(, %s9) # 8-byte Folded Spill
; CHECK-NEXT:    st %s19, 56(, %s9) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset %s18, 48
; CHECK-NEXT:    .cfi_offset %s19, 56
; CHECK-NEXT:    .cfi_remember_state
; CHECK-NEXT:    or %s18, 0, %s0
; CHECK-NEXT:  .Ltmp0: # EH_LABEL
; CHECK-NEXT:    lea %s0, foo@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, foo@hi(, %s0)
; CHECK-NEXT:    or %s0, 0, %s18
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:  .Ltmp1: # EH_LABEL
; CHECK-NEXT:  # %bb.1: # %done
; CHECK-NEXT:    ld %s19, 56(, %s9) # 8-byte Folded Reload
; CHECK-NEXT:    ld %s18, 48(, %s9) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore %s18
; CHECK-NEXT:    .cfi_restore %s19
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    .cfi_def_cfa %s11, 0
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    .cfi_restore %s10
; CHECK-NEXT:    .cfi_restore %s9
; CHECK-NEXT:    b.l.t (, %s10)
; CHECK-NEXT:  .LBB0_2: # %lpad
; CHECK-NEXT:    .cfi_restore_state
; CHECK-NEXT:  .Ltmp2: # EH_LABEL
; CHECK-NEXT:    or %s19, 0, %s0
; CHECK-NEXT:    lea %s0, bar@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, bar@hi(, %s0)
; CHECK-NEXT:    or %s0, 0, %s18
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    lea %s0, _Unwind_Resume@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, _Unwind_Resume@hi(, %s0)
; CHECK-NEXT:    or %s0, 0, %s19
; CHECK-NEXT:    bsic %s10, (, %s12)
entry:
  invoke void @foo(ptr %p) to label %done unwind label %lpad

lpad:
  %0 = landingpad { ptr, i32 } cleanup
  call void @bar(ptr %p)
  resume { ptr, i32 } %0

done:
  ret void
}

; Test catch landingpad
define void @catch(ptr %p) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: catch:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    .cfi_offset %s9, 0
; CHECK-NEXT:    .cfi_offset %s10, 8
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    .cfi_def_cfa_register %s9
; CHECK-NEXT:    .cfi_remember_state
; CHECK-NEXT:    lea %s11, -240(, %s11)
; CHECK-NEXT:    brge.l %s11, %s8, .LBB1_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB1_4: # %entry
; CHECK-NEXT:  .Ltmp3: # EH_LABEL
; CHECK-NEXT:    lea %s1, foo@lo
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    lea.sl %s12, foo@hi(, %s1)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:  .Ltmp4: # EH_LABEL
; CHECK-NEXT:  .LBB1_2: # %done
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    .cfi_def_cfa %s11, 0
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    .cfi_restore %s10
; CHECK-NEXT:    .cfi_restore %s9
; CHECK-NEXT:    b.l.t (, %s10)
; CHECK-NEXT:  .LBB1_1: # %lpad
; CHECK-NEXT:    .cfi_restore_state
; CHECK-NEXT:  .Ltmp5: # EH_LABEL
; CHECK-NEXT:    lea %s1, bar@lo
; CHECK-NEXT:    and %s1, %s1, (32)0
; CHECK-NEXT:    lea.sl %s12, bar@hi(, %s1)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    br.l.t .LBB1_2
entry:
  invoke void @foo(ptr %p) to label %done unwind label %lpad

lpad:
  %0 = landingpad { ptr, i32 }
    catch ptr null
  %1 = extractvalue { ptr, i32 } %0, 0
  call void @bar(ptr %1)
  ret void

done:
  ret void
}
