; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=ve-unknown-linux-gnu | FileCheck %s

declare void @func(ptr)
declare i32 @callee()

;; -fstack-protector: large char buffer (>= 8 bytes) triggers protection.
define void @test_ssp_large_buffer() #0 {
; CHECK-LABEL: test_ssp_large_buffer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -512(, %s11)
; CHECK-NEXT:    brge.l %s11, %s8, .LBB0_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB0_4: # %entry
; CHECK-NEXT:    ld %s0, 16(, %s14)
; CHECK-NEXT:    st %s0, -8(, %s9)
; CHECK-NEXT:    lea %s0, func@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, func@hi(, %s0)
; CHECK-NEXT:    lea %s0, -264(, %s9)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    ld %s0, -8(, %s9)
; CHECK-NEXT:    ld %s1, 16(, %s14)
; CHECK-NEXT:    brne.l %s1, %s0, .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
; CHECK-NEXT:  .LBB0_2: # %entry
; CHECK-NEXT:    lea %s0, __stack_chk_fail@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, __stack_chk_fail@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
entry:
  %buf = alloca [256 x i8], align 1
  call void @func(ptr %buf)
  ret void
}

;; -fstack-protector-strong: small char buffer (< 8 bytes) triggers protection.
define void @test_sspstrong_small_buffer() #1 {
; CHECK-LABEL: test_sspstrong_small_buffer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -256(, %s11)
; CHECK-NEXT:    brge.l %s11, %s8, .LBB1_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB1_4: # %entry
; CHECK-NEXT:    ld %s0, 16(, %s14)
; CHECK-NEXT:    st %s0, -8(, %s9)
; CHECK-NEXT:    lea %s0, func@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, func@hi(, %s0)
; CHECK-NEXT:    lea %s0, -12(, %s9)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    ld %s0, -8(, %s9)
; CHECK-NEXT:    ld %s1, 16(, %s14)
; CHECK-NEXT:    brne.l %s1, %s0, .LBB1_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
; CHECK-NEXT:  .LBB1_2: # %entry
; CHECK-NEXT:    lea %s0, __stack_chk_fail@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, __stack_chk_fail@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
entry:
  %buf = alloca [4 x i8], align 1
  call void @func(ptr %buf)
  ret void
}

;; -fstack-protector: small char buffer does NOT trigger protection.
define void @test_ssp_small_buffer() #0 {
; CHECK-LABEL: test_ssp_small_buffer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -256(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB2_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB2_2: # %entry
; CHECK-NEXT:    lea %s0, func@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, func@hi(, %s0)
; CHECK-NEXT:    lea %s0, -4(, %s9)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
entry:
  %buf = alloca [4 x i8], align 1
  call void @func(ptr %buf)
  ret void
}

;; -fstack-protector-all: no buffer, just a function call, triggers protection.
define i32 @test_sspreq_no_buffer() #2 {
; CHECK-LABEL: test_sspreq_no_buffer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -256(, %s11)
; CHECK-NEXT:    brge.l %s11, %s8, .LBB3_4
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB3_4: # %entry
; CHECK-NEXT:    ld %s0, 16(, %s14)
; CHECK-NEXT:    st %s0, -8(, %s9)
; CHECK-NEXT:    lea %s0, callee@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, callee@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    ld %s1, -8(, %s9)
; CHECK-NEXT:    ld %s2, 16(, %s14)
; CHECK-NEXT:    brne.l %s2, %s1, .LBB3_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
; CHECK-NEXT:  .LBB3_2: # %entry
; CHECK-NEXT:    lea %s0, __stack_chk_fail@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, __stack_chk_fail@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
entry:
  %ret = call i32 @callee()
  ret i32 %ret
}

;; -fstack-protector-strong: no buffer, just a function call, does NOT trigger.
define i32 @test_sspstrong_no_buffer() #1 {
; CHECK-LABEL: test_sspstrong_no_buffer:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    st %s9, (, %s11)
; CHECK-NEXT:    st %s10, 8(, %s11)
; CHECK-NEXT:    or %s9, 0, %s11
; CHECK-NEXT:    lea %s11, -240(, %s11)
; CHECK-NEXT:    brge.l.t %s11, %s8, .LBB4_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    ld %s61, 24(, %s14)
; CHECK-NEXT:    or %s62, 0, %s0
; CHECK-NEXT:    lea %s63, 315
; CHECK-NEXT:    shm.l %s63, (%s61)
; CHECK-NEXT:    shm.l %s8, 8(%s61)
; CHECK-NEXT:    shm.l %s11, 16(%s61)
; CHECK-NEXT:    monc
; CHECK-NEXT:    or %s0, 0, %s62
; CHECK-NEXT:  .LBB4_2: # %entry
; CHECK-NEXT:    lea %s0, callee@lo
; CHECK-NEXT:    and %s0, %s0, (32)0
; CHECK-NEXT:    lea.sl %s12, callee@hi(, %s0)
; CHECK-NEXT:    bsic %s10, (, %s12)
; CHECK-NEXT:    or %s11, 0, %s9
; CHECK-NEXT:    ld %s10, 8(, %s11)
; CHECK-NEXT:    ld %s9, (, %s11)
; CHECK-NEXT:    b.l.t (, %s10)
entry:
  %ret = call i32 @callee()
  ret i32 %ret
}

attributes #0 = { nounwind ssp }
attributes #1 = { nounwind sspstrong }
attributes #2 = { nounwind sspreq }
